import { MetadataRoute } from "next"

import { siteConfig } from "@/config/site"

export const dynamic = "force-static"

/**
 * Answer engines (ChatGPT, Claude, Perplexity, Gemini, Copilot) only cite
 * sources they are permitted to fetch, and several of them respect a distinct
 * user-agent from the classic search crawler. Listing them explicitly makes the
 * archive citable rather than relying on a generous reading of the wildcard.
 */
const AI_CRAWLERS = [
  "GPTBot",
  "OAI-SearchBot",
  "ChatGPT-User",
  "ClaudeBot",
  "Claude-User",
  "Claude-SearchBot",
  "anthropic-ai",
  "PerplexityBot",
  "Perplexity-User",
  "Google-Extended",
  "Applebot",
  "Applebot-Extended",
  "cohere-ai",
  "meta-externalagent",
  "Amazonbot",
  "DuckAssistBot",
  "YouBot",
]

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [],
      },
      {
        userAgent: AI_CRAWLERS,
        allow: "/",
      },
    ],
    // A sitemap index. Its segments (pages, services, messages, roadmap) are
    // generated by scripts/build-public-feeds.mjs; submitting them individually
    // in Search Console gives a per-section indexed count, which is the only
    // way to see which part of the archive a crawler is actually taking.
    sitemap: `${siteConfig.url}/sitemap.xml`,
    // No `host`: it is a Yandex-only directive that Yandex itself retired, and
    // every other crawler reports it as an unknown directive.
  }
}
